export { Button } from './Button/Button'
export { Skills } from './Skills/Skills'
export { Social } from './Social/Social'
export { Tabs } from './Tabs/Tabs'
export {AboutSection} from './AboutSection/AboutSection'
export {HomeSection} from './HomeSection/HomeSection'
export {WorksSection} from './WorksSection/WorksSection'
export {WorkCard} from './WorksCard/WorkCard'
export {GoBack} from './GoBack/GoBack'